// DEVELOPMENT URL
// export const kBaseUrl = "https://app-lightbox.herokuapp.com/api/";

// PRODUCTION URL
export const kBaseUrl = "https://lightboxnode.herokuapp.com/api/";

// LOCAL DEELOPMENT URL
// export const kBaseUrl = "http://localhost:3000/api/";

export const branchList = [
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Electronics and Communication",
  "Information Technology",
  "Instrumentation and Control",
  "Mechanical Engineering",
  "Power Electronics",
];

export const generalSkillSet = [
  { label: "Adobe Illustrator", value: "Adobe Illustrator" },
  { label: "Adobe Photoshop", value: "Adobe Photoshop" },
  { label: "Adobe Premier Pro", value: "Adobe Premier Pro" },
  { label: "Adobe XD", value: "Adobe XD" },
  { label: "Algorithms", value: "Algorithms" },
  { label: "Android", value: "Android" },
  { label: "Angular", value: "Angular" },
  { label: "AngularJS", value: "AngularJS" },
  { label: "Ansys", value: "Ansys" },
  { label: "App Development", value: "App Development" },
  { label: "Arduino", value: "Arduino" },
  { label: "Artificial Intelligence", value: "Artificial Intelligence" },
  { label: "Atmel", value: "Atmel" },
  { label: "Augmented Reality", value: "Augmented Reality" },
  { label: "AUTOCAD", value: "AUTOCAD" },
  { label: "AWS", value: "AWS" },
  { label: "BackboneJS", value: "BackboneJS" },
  { label: "Bash", value: "Bash" },
  { label: "Big Data Analytics", value: "Big Data Analytics" },
  { label: "Blockchain", value: "Blockchain" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Business Intelligence", value: "Business Intelligence" },
  { label: "C", value: "C" },
  { label: "C#", value: "C#" },
  { label: "C++", value: "C++" },
  { label: "CakePHP", value: "CakePHP" },
  { label: "Cassandra", value: "Cassandra" },
  { label: "Chemlab", value: "Chemlab" },
  { label: "Cloud Computing", value: "Cloud Computing" },
  { label: "Competitive Coding", value: "Competitive Coding" },
  { label: "Computer Network", value: "Computer Network" },
  { label: "CSS", value: "CSS" },
  { label: "Cyber Security", value: "Cyber Security" },
  { label: "Dart", value: "Dart" },
  { label: "Data Analysis", value: "Data Analysis" },
  { label: "Data Mining", value: "Data Mining" },
  { label: "Data Science", value: "Data Science" },
  { label: "Data Structures", value: "Data Structures" },
  { label: "Database Design", value: "Database Design" },
  { label: "DBMS", value: "DBMS" },
  { label: "Deep Learning", value: "Deep Learning" },
  { label: "DevOps", value: "DevOps" },
  { label: "Django", value: "Django" },
  { label: "Docker", value: "Docker" },
  { label: "Dot Net", value: "Dot Net" },
  { label: "Dreamwaver", value: "Dreamwaver" },
  { label: "E - Tabs", value: "E - Tabs" },
  { label: "Eagle", value: "Eagle" },
  { label: "Eclipse", value: "Eclipse" },
  { label: "ElectronJS", value: "ElectronJS" },
  { label: "EmberJS", value: "EmberJS" },
  { label: "Figma", value: "Figma" },
  { label: "Firebase", value: "Firebase" },
  { label: "Flutter", value: "Flutter" },
  { label: "GCP", value: "GCP" },
  { label: "Git", value: "Git" },
  { label: "Go lang", value: "Go lang" },
  { label: "Google Ads", value: "Google Ads" },
  { label: "Google Analytics", value: "Google Analytics" },
  { label: "Google Dialogflow", value: "Google Dialogflow" },
  { label: "GraphQL", value: "GraphQL" },
  { label: "Hadoop", value: "Hadoop" },
  { label: "Heroku", value: "Heroku" },
  { label: "Hibernate", value: "Hibernate" },
  { label: "HTML", value: "HTML" },
  { label: "Image Processing", value: "Image Processing" },
  { label: "Ionic", value: "Ionic" },
  { label: "IOT", value: "IOT" },
  { label: "J2EE", value: "J2EE" },
  { label: "Java", value: "Java" },
  { label: "JavaScript", value: "JavaScript" },
  { label: "Jenkins", value: "Jenkins" },
  { label: "Joomla", value: "Joomla" },
  { label: "JQuery", value: "JQuery" },
  { label: "JSON", value: "JSON" },
  { label: "JSP", value: "JSP" },
  { label: "KeyStoneJS", value: "KeyStoneJS" },
  { label: "Kotlin", value: "Kotlin" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Laravel", value: "Laravel" },
  { label: "LaTeX", value: "LaTeX" },
  { label: "Leadership", value: "Leadership" },
  { label: "LESS", value: "LESS" },
  { label: "Linux", value: "Linux" },
  { label: "Machine Learning", value: "Machine Learning" },
  { label: "Magento", value: "Magento" },
  { label: "MATLAB", value: "MATLAB" },
  { label: "Maven", value: "Maven" },
  { label: "Microcontroller", value: "Microcontroller" },
  { label: "Microsft Azure", value: "Microsft Azure" },
  { label: "Microsft Excel", value: "Microsft Excel" },
  { label: "Microsft Powerpoint", value: "Microsft Powerpoint" },
  { label: "Microsft Word", value: "Microsft Word" },
  { label: "Microsoft Access", value: "Microsoft Access" },
  { label: "Microsoft Power BI", value: "Microsoft Power BI" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "MySQL", value: "MySQL" },
  { label: "Neural Network", value: "Neural Network" },
  { label: "NextJS", value: "NextJS" },
  { label: "NginX", value: "NginX" },
  { label: "NLP", value: "NLP" },
  { label: "NodeJS", value: "NodeJS" },
  { label: "NodeMCU", value: "NodeMCU" },
  { label: "NoSQL", value: "NoSQL" },
  { label: "OAuth", value: "OAuth" },
  {
    label: "Object Oriented Programming",
    value: "Object Oriented Programming",
  },
  { label: "Objective C", value: "Objective C" },
  { label: "OODO", value: "OODO" },
  { label: "OpenCV", value: "OpenCV" },
  { label: "ORCADE", value: "ORCADE" },
  { label: "Pascal", value: "Pascal" },
  { label: "PCB Designing", value: "PCB Designing" },
  { label: "Perl", value: "Perl" },
  { label: "PHP", value: "PHP" },
  { label: "Postman tool", value: "Postman tool" },
  { label: "PostgreSQL", value: "PostgreSQL" },
  { label: "Postwoman tool", value: "Postwoman tool" },
  { label: "PowerBuilder", value: "PowerBuilder" },
  { label: "Python", value: "Python" },
  { label: "R", value: "R" },
  { label: "Raspberry PI", value: "Raspberry PI" },
  { label: "React Native", value: "React Native" },
  { label: "ReactJS", value: "ReactJS" },
  { label: "REST APIs", value: "REST APIs" },
  { label: "Revit", value: "Revit" },
  { label: "Rhino 3D", value: "Rhino 3D" },
  { label: "Robotics", value: "Robotics" },
  { label: "Ruby", value: "Ruby" },
  { label: "Ruby On Rails", value: "Ruby On Rails" },
  { label: "SASS", value: "SASS" },
  { label: "Scala", value: "Scala" },
  { label: "SEO", value: "SEO" },
  { label: "Servlet", value: "Servlet" },
  { label: "Simulink", value: "Simulink" },
  { label: "Software Development", value: "Software Development" },
  { label: "Soldering", value: "Soldering" },
  { label: "Solid Works", value: "Solid Works" },
  { label: "Spring Frameworks", value: "Spring Frameworks" },
  { label: "SQL", value: "SQL" },
  { label: "Stadd Pro", value: "Stadd Pro" },
  { label: "Structural Engineering", value: "Structural Engineering" },
  { label: "Surveying", value: "Surveying" },
  { label: "Swift", value: "Swift" },
  { label: "Tableu", value: "Tableu" },
  { label: "Team Management", value: "Team Management" },
  { label: "TypeScript", value: "TypeScript" },
  { label: "UI/UX Designing", value: "UI/UX Designing" },
  { label: "UNITY", value: "UNITY" },
  { label: "Unreal Engine", value: "Unreal Engine" },
  { label: "Unix Shell", value: "Unix Shell" },
  { label: "Video Editing", value: "Video Editing" },
  { label: "Virtual Reality", value: "Virtual Reality" },
  { label: "VLSI", value: "VLSI" },
  { label: "VueJS", value: "VueJS" },
  { label: "Web Development", value: "Web Development" },
  { label: "WordPress", value: "WordPress" },
  { label: "Xamarin", value: "Xamarin" },
  { label: "XHTML", value: "XHTML" },
  { label: "XML", value: "XML" },
  { label: "Adaptibility", value: "Adaptibility" },
  { label: "Communication", value: "Communication" },
  { label: "Content Writing", value: "Content Writing" },
  { label: "Creativity", value: "Creativity" },
  { label: "Critical Thinking", value: "Critical Thinking" },
  { label: "Crowd Control", value: "Crowd Control" },
  { label: "Decision Making", value: "Decision Making" },
  { label: "Drawing", value: "Drawing" },
  { label: "Flexibility", value: "Flexibility" },
  { label: "Graphic Designing", value: "Graphic Designing" },
  { label: "Hardworking", value: "Hardworking" },
  { label: "Karate", value: "Karate" },
  { label: "Leadership", value: "Leadership" },
  { label: "Logo Designing", value: "Logo Designing" },
  { label: "Management", value: "Management" },
  { label: "Mandala Art", value: "Mandala Art" },
  { label: "Orator", value: "Orator" },
  { label: "Painting", value: "Painting" },
  { label: "Photography", value: "Photography" },
  { label: "Poetry", value: "Poetry" },
  { label: "Presentation Skills", value: "Presentation Skills" },
  { label: "Problem Solving", value: "Problem Solving" },
  { label: "Public Speaking", value: "Public Speaking" },
  { label: "Reading", value: "Reading" },
  { label: "Singing", value: "Singing" },
  { label: "Sportsmanship", value: "Sportsmanship" },
  { label: "Story Telling", value: "Story Telling" },
  { label: "Story Writing", value: "Story Writing" },
  { label: "Strategical Planning", value: "Strategical Planning" },
  { label: "Street Play", value: "Street Play" },
  { label: "Team Management", value: "Team Management" },
  { label: "Video Editing", value: "Video Editing" },
];

//{label:"Adaptibility",value:"Adaptibility"},{label:"Communication",value:"Communication"},{label:"Content Writing",value:"Content Writing"},{label:"Creativity",value:"Creativity"},{label:"Critical Thinking",value:"Critical Thinking"},{label:"Crowd Control",value:"Crowd Control"},{label:"Decision Making",value:"Decision Making"},{label:"Drawing",value:"Drawing"},{label:"Flexibility",value:"Flexibility"},{label:"Graphic Designing",value:"Graphic Designing"},{label:"Hardworking",value:"Hardworking"},{label:"Karate",value:"Karate"},{label:"Leadership",value:"Leadership"},{label:"Logo Designing",value:"Logo Designing"},{label:"Management",value:"Management"},{label:"Mandala Art",value:"Mandala Art"},{label:"Orator",value:"Orator"},{label:"Painting",value:"Painting"},{label:"Photography",value:"Photography"},{label:"Poetry",value:"Poetry"},{label:"Presentation Skills",value:"Presentation Skills"},{label:"Problem Solving",value:"Problem Solving"},{label:"Public Speaking",value:"Public Speaking"},{label:"Reading",value:"Reading"},{label:"Singing",value:"Singing"},{label:"Sportsmanship",value:"Sportsmanship"},{label:"Story Telling",value:"Story Telling"},{label:"Story Writing",value:"Story Writing"},{label:"Strategical Planning",value:"Strategical Planning"},{label:"Street Play",value:"Street Play"},{label:"Team Management",value:"Team Management"},{label:"Video Editing",value:"Video Editing"}
